start python main.py ./config1
start python main.py ./config2
start python main.py ./config3
start python main.py ./config4
start python main.py ./config5
start python main.py ./config6
start python main.py ./config7
start python main.py ./config8
start python main.py ./config9
start python main.py ./config10
start python main.py ./config11
start python main.py ./config12
start python main.py ./config13
start python main.py ./config14
start python main.py ./config15
start python main.py ./config16
