start python main.py ../config/config1
start python main.py ../config/config2
start python main.py ../config/config3
start python main.py ../config/config4
start python main.py ../config/config5
start python main.py ../config/config6
start python main.py ../config/config7
start python main.py ../config/config8
start python main.py ../config/config9
start python main.py ../config/config10
start python main.py ../config/config11
start python main.py ../config/config12
start python main.py ../config/config13
start python main.py ../config/config14
start python main.py ../config/config15
start python main.py ../config/config16
